[pins]
scan = [22, 10, 9, 11, 5, 6, 13, 19, 26]
out = [25, 8, 7, 1, 12, 16, 20, 21]

[mod]
9.7 = "SHFT"
1.4 = "CODE"

[codepoint]
2.3.NONE = 0x71 # q
2.3.SHFT = 0x51 # Q
2.5.NONE = 0x61 # a
2.5.SHFT = 0x41 # A
2.6.NONE = 0x73 # s
2.6.SHFT = 0x53 # S
2.7.NONE = 0x79 # y
2.7.SHFT = 0x59 # Y
2.8.CODE = 0xB2 # ²
2.8.NONE = 0x78 # x
2.8.SHFT = 0x58 # X
3.1.NONE = 0x31 # 1
3.1.SHFT = 0x21 # !
3.2.NONE = 0x32 # 2
3.2.SHFT = 0x22 # "
3.3.NONE = 0x65 # e
3.3.SHFT = 0x45 # E
3.4.CODE = 0x9E # °
3.4.NONE = 0x77 # w
3.4.SHFT = 0x57 # W
3.5.NONE = 0x64 # d
3.5.SHFT = 0x44 # D
3.6.NONE = 0x66 # f
3.6.SHFT = 0x46 # F
3.7.NONE = 0x63 # c
3.7.SHFT = 0x43 # C
3.8.CODE = 0xB3 # ³
3.8.NONE = 0x76 # v
3.8.SHFT = 0x56 # V
4.1.NONE = 0x33 # 3
4.1.SHFT = 0xA7 # §
4.2.NONE = 0x34 # 4
4.2.SHFT = 0x24 # $
4.3.NONE = 0x74 # t
4.3.SHFT = 0x54 # T
4.4.NONE = 0x72 # r
4.4.SHFT = 0x52 # R
4.5.NONE = 0x67 # g
4.5.SHFT = 0x47 # G
4.6.NONE = 0x68 # h
4.6.SHFT = 0x48 # H
4.7.NONE = 0x62 # b
4.7.SHFT = 0x42 # B
4.8.NONE = 0x6E # n
4.8.SHFT = 0x4E # N
5.1.NONE = 0x35 # 5
5.1.SHFT = 0x25 # %
5.2.NONE = 0x36 # 6
5.2.SHFT = 0x26 # &
5.3.CODE = 0xB5 # µ
5.3.NONE = 0x75 # u
5.3.SHFT = 0x55 # U
5.4.NONE = 0x7A # z
5.4.SHFT = 0x5A # Z
5.5.NONE = 0x6A # j
5.5.SHFT = 0x4A # J
5.6.NONE = 0x6B # k
5.6.SHFT = 0x4B # K
5.7.NONE = 0x6D # m
5.7.SHFT = 0x4D # M
5.8.NONE = 0x2C # ,
5.8.SHFT = 0x3B # ;
6.1.NONE = 0x37 # 7
6.1.SHFT = 0x2F # /
6.2.NONE = 0x38 # 8
6.2.SHFT = 0x28 # (
6.3.NONE = 0x6F # o
6.3.SHFT = 0x4F # O
6.4.NONE = 0x69 # i
6.4.SHFT = 0x49 # I
6.5.NONE = 0x6C # l
6.5.SHFT = 0x4C # L
6.6.NONE = 0xF6 # ö
6.6.SHFT = 0xD6 # Ö
6.7.NONE = 0x2E # .
6.7.SHFT = 0x3A # :
6.8.NONE = 0x2D # -
6.8.SHFT = 0x5F # _
7.1.NONE = 0x39 # 9
7.1.SHFT = 0x29 # )
7.2.NONE = 0x30 # 0
7.2.SHFT = 0x3D # =
7.3.NONE = 0xFC # ü
7.3.SHFT = 0xDC # Ü
7.4.NONE = 0x70 # p
7.4.SHFT = 0x50 # P
7.5.NONE = 0xE4 # ä
7.5.SHFT = 0xC4 # Ä
7.6.NONE = 0x23 # #
7.6.SHFT = 0x27 # '
7.7.NONE = 0xDF # ß
7.7.SHFT = 0x3F # ?
8.2.NONE = 0xB4 # ´
8.2.SHFT = 0x60 # `
8.4.NONE = 0x2B # +
8.4.SHFT = 0x2A # *
8.5.NONE = 0x0A # LF
8.6.NONE = 0x08 # Backspace
8.8.NONE = 0x20 # SPACE

[key]
1.1.NONE = 0x83 # Pitch
1.2.NONE = 0x84 # Line
1.3.NONE = 0x85 # LMAR
1.3.CODE = 0x86 # RMAR
1.5.NONE = 0x88 # T+
1.5.CODE = 0x89 # T-
1.6.NONE = 0x8A # Caps Lock
1.8.CODE = 0x8B # LINE OUT
1.8.NONE = 0x81 # WORD OUT
2.2.CODE = 0x8C # L IND Top
2.2.NONE = 0x8E # Return L Top
2.4.CODE = 0x8D # L IND Bot
2.4.NONE = 0x8F # Return L Bot
7.8.CODE = 0x90 # Backspace !!!!!!!!!!!!!!!!!!!! \b?
8.1.NONE = 0x91 # <-||->
8.3.CODE = 0x93 # |-<-|
8.3.NONE = 0x92 # RELOC
8.6.CODE = 0x95 # <<-
8.6.NONE = 0x94 # |<-|
8.7.CODE = 0x97 # REV
8.7.NONE = 0x96 # INDEX
6.1.CODE = 0xA6 # AUTORETURN ON
6.2.CODE = 0xA7 # AUTORETURN OFF
7.1.CODE = 0xA8 # DOWN
7.2.CODE = 0xA9 # UP
4.2.CODE = 0xAA # UNDERLINE ON
5.1.CODE = 0xAB # UNDERLINE OFF
3.2.CODE = 0xAC # CTR
4.1.CODE = 0xAD # RMF
